# Rule list: https://github.com/realm/SwiftLint/blob/master/Rules.md

disabled_rules:
  - discarded_notification_center_observer
  - empty_enum_arguments
  - force_cast
  - multiple_closures_with_trailing_closure # This rule conflicts with Xcode autocomplete syntax
  - no_fallthrough_only
  - notification_center_detachment

opt_in_rules:
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_types_order
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet 
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

included:
  - ToolReleases
  - ToolReleasesCore

excluded:
  - Pods

cyclomatic_complexity:
  warning: 10
  error: 20

file_length:
  warning: 150
  error: 200

function_body_length:
  warning: 20
  error: 40

identifier_name:
  min_length: 3
  max_length:
    warning: 75
    error: 100
  excluded:
    - i
    - id
    - on
    - up
    - vc
    - nc

line_length:
  warning: 200
  error: 250
  ignores_function_declarations: true
  ignores_comments: true

nesting:
  type_level: 3

type_name:
  min_length: 3
  max_length:
    warning: 75
    error: 100
