name: Tests

on:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'ToolReleases/**'
      - 'ToolReleasesCore/**'
      - 'ToolReleasesTests/**'
      - 'ToolReleasesCoreTests/**'

jobs:
  test:
    name: Unit tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.2.app

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -clonedSourcePackagesDirPath .build

      - name: Clean project
        run: |
          set -o pipefail
          xcodebuild -clonedSourcePackagesDirPath .build clean

      - name: Build
        run: |
          set -o pipefail
          xcodebuild -clonedSourcePackagesDirPath .build -scheme ToolReleases -destination platform=macOS build-for-testing | xcpretty

      - name: Test
        run: |
          set -o pipefail
          xcodebuild -clonedSourcePackagesDirPath .build -scheme ToolReleases -destination platform=macOS test-without-building | xcpretty
